markdown: redcarpet
redcarpet:
    extensions: ["with_toc_data"]
permalink: /:year/:month/:title/

## Metadata
title: Sergey.Makoveev.info
tagline: The personal site of Sergey Makoveev, a web developer
keywords: [js, css, css3, css4, html, html5, web api, js api, development, jquery, frontend, фронтенд]
description: The personal site of Sergey Makoveev, a web developer
divider: ' · '

author:
    name:
        ru: Сергей Маковеев
        en: Sergey Makoveev
    avatar: http://www.gravatar.com/avatar/ec5c4ece917e78fe539d3051f4cbb87b.png?s=200
    email: sergey@makoveev.info
    url: http://sergey.makoveev.info
    twitter:
        name: @sergeymakoveev
        url: http://twitter.com/sergeymakoveev
    github:
        name: sergeymakoveev
        url: https://github.com/sergeymakoveev
    google:
        name: 102114895580046085377
        url: https://plus.google.com/102114895580046085377/?rel=author
    facebook:
        name: sergey.makoveev.info
        url: https://facebook.com/sergey.makoveev.info
        id: 100000275357914

host: http://sergeymakoveev.github.com
logo: http://www.gravatar.com/avatar/ec5c4ece917e78fe539d3051f4cbb87b.png?s=200
favicon: /favicon.ico
google-analytics: 111111
