markdown: redcarpet
permalink: /:year/:month/:title/

## Metadata
title: Sergey.Makoveev.info
tagline: The personal site of Sergey Makoveev, a web developer
keywords: [js, css, css3, css4, html, html5, web api, js api, development, jquery, frontend, фронтенд]
description: The personal site of Sergey Makoveev, a web developer
divider: ' · '

author:
    name:
        ru: Сергей Маковеев
        en: Sergey Makoveev
    avatar: http://www.gravatar.com/avatar/ec5c4ece917e78fe539d3051f4cbb87b.png?s=200
    email: sergey@makoveev.info
    url: http://sergey.makoveev.info
    github: https://github.com/sergeymakoveev
    google: https://plus.google.com/102114895580046085377/?rel=author
    facebook: sergey.makoveev.info

host: http://sergeymakoveev.github.com
