exclude: [ Gemfile, Gemfile.lock, Procfile, vendor, config.ru, Rakefile, readme.md, start.sh ]

name: sergey
highlighter: null
permalink: /:year/:month/:title/
markdown: kramdown

kramdown:
  enable_coderay: false

## Metadata
meta:
    title: Sergey.Makoveev.info
    tagline: The personal site of Sergey Makoveev, a web developer
    keywords: [js, css, html, web api, js api, javascript, frontend, фронтенд]
    description: The personal site of Sergey Makoveev, a web developer
    divider: ' · '

    author:
        name:
            ru: Сергей Маковеев
            en: Sergey Makoveev
        avatar: //www.gravatar.com/avatar/ec5c4ece917e78fe539d3051f4cbb87b.png?s=200
        email: sergey@makoveev.info
        url: http://sergey.makoveev.info
        bitbucket:
            name: sergeymakoveev
            url: https://bitbucket.org/sergeymakoveev
        twitter:
            name: '@sergeymakoveev'
            url: http://twitter.com/sergeymakoveev
        github:
            name: sergeymakoveev
            url: https://github.com/sergeymakoveev
        google:
            name: +СергейМаковеев
            url: https://plus.google.com/+СергейМаковеев/?rel=author
            id: 102114895580046085377
        facebook:
            name: sergey.makoveev.info
            url: https://facebook.com/sergey.makoveev.info
            id: 100000275357914

    host: http://sergey.makoveev.info
    logo: //www.gravatar.com/avatar/ec5c4ece917e78fe539d3051f4cbb87b.png?s=200
    favicon: /favicon.ico

    services:
        google-analytics:
            id: UA-37914961-1
            domain: makoveev.info
        disqus: sergeymakoveev
