markdown: redcarpet
permalink: /:year/:month/:title/

## Metadata
title: Sergey.Makoveev.info
tagline: The personal site of Sergey Makoveev, a web developer
keywords: [js, css, css3, css4, html, html5, web api, js api, development, jquery, frontend, фронтенд]
description: The personal site of Sergey Makoveev, a web developer
author:
    name: Sergey Makoveev
    givenName: Sergey
    familyName: Makoveev
    email: sergey@makoveev.info
    twitter: @sergeymakoveev
    github: https://github.com/sergeymakoveev
    google: https://plus.google.com/102114895580046085377/?rel=author
